
services:
  mongo:
    image: mongo:8.0.0-rc20
    env_file: .env
    volumes:
      - mongodb-volume:/var/lib/mongodb/data
    ports:
      - 27017:27017
#  mongo-express:
#    image: mongo-express:1.0.2-20-alpine3.19
#    env_file: .env
#    volumes:
#      - mongo-express-volume:/var/lib/mongo-express/date


volumes:
  mongodb-volume:
#  mongo-express-volume:
