
spring:

  application:
    name: BRP-backend
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_DATABASE}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      authentication-database: admin
  profiles:
    active: dev
server:
  port: 8102

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
