spring.application.name=BRP-backend
sms.account_sid=${TWILIO_ACCOUNT_SID}
sms.auth.token=${TWILIO_AUTH_TOKEN}
sms.phoneNumber=${TWILIO_PHONE_NUMBER}
payment.api.key=${PAYSTACK_API_KEY}

server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=june12003
server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=june12003
server.ssl.key-store-type=JKS
server.ssl.key-alias=mycert


